### ISSUE TITLE
Crash/Close when importing some Sonic 2006 .xno files

### ISSUE THREAD

**Issue by roket333** [Argx2121/Sega_NN_tools#4]
When importing some .XNO files from Sonic 2006, Blender will crash when trying to make the mesh and sometimes when cleaning the mesh
[problematic.zip](https://github.com/Argx2121/Sega_NN_tools/files/6759245/problematic.zip)
Edited because it turns out it wasnt the batch import at all

**Comment by Sewer56** [comment]
neko

**Comment by Argx2121** [comment]
Fixed in the very big refactor update:
https://github.com/Argx2121/Sega_NN_tools/commit/b9a8a39b761c9d73ed38c8c0cde30c7b67049d55
