### ISSUE TITLE
Runtime error when importing model P270M from Sonic Riders GCN USA using Blender 3.3.0

### ISSUE THREAD

**Issue by jameswilddev** [Argx2121/Sega_NN_tools#5]
![image](https://user-images.githubusercontent.com/3138458/189399172-1c239e0a-f9a5-4749-b230-279caac76d5e.png)

Really hype to use these tools though, mad props!

**Comment by jameswilddev** [comment]
Aha I believe this is Blender version specific, installed an older version and it works fine.

**Comment by Argx2121** [comment]
I'm on 3.3.0. Did you unpack the files (cannot import packed models) and did you restart blender after installing an updated version?

**Comment by jameswilddev** [comment]
Reinstalling 3.3.0 fixed this.  Thanks, these tools are rockin'!
