### ISSUE TITLE
Error When Importing Models from Sonic the Hedgehog 4: Episode 1 (iOS, V. 1.0)

### ISSUE THREAD

**Issue by DogToon64** [Argx2121/Sega_NN_tools#7]
Whenever I try to import models from the iOS version of Sonic the Hedgehog 4: Episode 1, specifically version 1.0, Blender gives me the error shown in the screenshot below:
![s4ioserror](https://github.com/Argx2121/Sega_NN_tools/assets/159098439/1ad8b8ba-230e-4b4a-a7e6-af083f47bc27)

**Comment by DogToon64** [comment]
Just realized I forgot to share a few sample files:
[Sample Files.zip](https://github.com/Argx2121/Sega_NN_tools/files/14642682/Sample.Files.zip)

(I also included the texture as well.)

**Comment by Argx2121** [comment]
Hi! the correct setting to use when importing is the pre 2016 sonic 4 ino import. 
![image](https://github.com/Argx2121/Sega_NN_tools/assets/66618295/591def5a-7cc8-4e43-b58e-9568bd7e1811)
Do you mind telling me how you converted the textures and if they were flipped during the process?
They look upside down..
Thank you!

**Comment by DogToon64** [comment]
Hi, thanks, and sorry for the late reply! I used [PVRTexTool](https://cdn.imgtec.com/sdk/OFFLINE/PVRTexToolSetup-2023_R2.exe) to convert the texture to a .png file. When I exported it, it was upside down, which seems to be how it's supposed to look.
